name: chart_components
description: Diverse chart components for Flutter.
version: 0.0.1
author: Fernando Paredes Quesada<fgcan10@gmail.com>
homepage: 

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

