name: chart_components
description: Two chart components for Flutter. An animated bar chart with label, value, icon and bar color. An animated calendar grid chart based on the github calendar.
version: 0.1.1
author: Fernando Paredes Quesada<fgcan10@gmail.com>
homepage: https://github.com/fgcan10/chart_components

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

