name: chart_components
description: Diverse chart components for Flutter.
version: 0.0.2
author: Fernando Paredes Quesada<fgcan10@gmail.com>
homepage: https://github.com/fgcan10/chart_components

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

